### ISSUE TITLE
[BUG] S99moonraker_obico needs to be renamed to work with moonraker svc

### ISSUE THREAD

**Issue by jynolen** [TheSpaghettiDetective/moonraker-obico#103]
**Describe the bug**
The way supervisorctl is done on Creality K1 is by checking the pid based on init.d filename.

ie. if the is named `S17-fooooooo_baaarrrr` the supervisorctl will assume a pid file named `fooooooo_baaarrrr.pid`

Even if another pid is setup within the init;d file.

Since in "S99moonraker_obico" the pid is moonraker-obico.pid the filename should be renamed accordinly (or pid file must match with underscore)

**Comment by kennethjiang** [comment]
Sorry for the delay.

I'm not sure if I understand your point here, probably because I'm not super familiar with how supervisorctl. I made the service script to a point that it seems to have worked. But it's possible it has some other flaws.

Maybe you can re-phrase your point so that I can understand what is impacted by this issue? Or maybe you can submit a PR to fix it? I think I will understand it better if I can see how you'd fix it.
